name: timurkham
favicon: null
layout_spectrum: 0.50494
typography_spectrum: 0.21476
title: Casa Mona
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0a09'
    - '#fcfafd'
    - '#30221f'
    - '#53391e'
    - '#9b6c35'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
